# Site settings
title: Rohit Taneja 
Linkedin: https://www.linkedin.com/in/rohit23taneja
name: Rohit Taneja

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://developer.nvidia.com/blog/author/rohit-taneja/
 - title: Google Scholar
   url: https://scholar.google.com/citations?user=CrxLWLwAAAAJ&hl=en 
 - title: GitHub
   url: https://github.com/taneja-rohit
 - title: LinkedIn
   url: https://www.linkedin.com/in/rohit23taneja

#Any buzzword skills you want to include
skills:
 - AI Infra Product Management
 - Negotiation and pricing 
 - PaaS  
 - Business models 
 - CLoud native development
 - API design and delivery
 - Data flows and Architecture
 - Distributing computing - Apache Spark 
 
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://developer.nvidia.com/blog/author/rohit-taneja/

#Work experience is required
roles:
 - title: Leadership Development 
   start: 2024
   end: 2025 
   employer: Harvard
   description: Leadership Development Program
 - title: Lead Product Manager
   start: 2021
   end: Ongoing
   employer: NVIDIA
   description: • DGX Cloud MVP business model for Top-20 customers/Hyperscalar-level pre-training.
                • Day 2 playbook for data manageibility and partnerships with CSP on ingress/egress and staging.
                • 1000+ fine-tuning jobs on fine-tuning with DGX Cloud via Hugging Face front-end with pay-as-you-go B2B2B business model. 
                • Successful internal alignment on standardized API spec for GPU consumption in managed service mode via partners. 
                • 10+ model and data partners onboarded for NVIDIA Inference microservices (NIM) adoption. 
 - title: Lead Product Manager
   start: 2021
   end: Ongoing
   employer: NVIDIA
   description: • DGX Cloud MVP business model for Top-20 customers/Hyperscalar-level pre-training.
                • Day 2 playbook for data manageibility and partnerships with CSP on ingress/egress and staging.
                • 1000+ fine-tuning jobs on fine-tuning with DGX Cloud via Hugging Face front-end with pay-as-you-go B2B2B business model. 
                • Successful internal alignment on standardized API spec for GPU consumption in managed service mode via partners. 
                • 10+ model and data partners onboarded for NVIDIA Inference microservices (NIM) adoption. 
 - title: Product Lead, AI/ML Infra 
   start: 2019
   end: 2021
   employer: Apple
   description: • Responsible for applying 2D Deep Learning models in Apple factories for Capex savings and yield improvements of Iphone Line of Business.
                • Responsible for data movement to centralized data management and real time processing of model inference. 
                • Managed global teams for building and deploying Infra for always-ON inference platform using on-prem and CSP utilities. 
                • Responsible for building data and model drift observability platform and flows.  
                • Responsible for scaling the product from single Apple Line of Business to across all Apple products, resulting in $50M+ savings for Apple manufacturing. 
 - title: Senior Performance Engineer
   start: 2013
   end: 2016
   employer: IBM
   description: • Responsible for setting up distributed data processing pipeline using Apache Spark on Hadoop Data lake
                • Responsible for working with Major CSPs to show value of IBM solution for fastest shuffle + sorting performance. 
                • Led team to put a streaming and batch processing pipeline for enterprise use-case with Apache Spark. 
                • Worked with research to optimize IBM compute architecture for contemporary workloads like Spark in-memory processing and Deep learning workloads. 
                • Awarded patents in the process of working with research around distributed processing and helping take IBM's effort to US National Laboratories. 
                • Got eligibility for Einstein Visa and got Green Card in Einstein visa category due to work done with IBM engineering and research teams and results delivered to enhance US technology. 

#Education is required
education:
 - level: M.S., Computer Engineering 
   date: 2011
   subject: Computer Science and Engineering with Research Thesis. 
   Title: Research Assistant in NSF funded embedded computing lab
   school: North Carolina State University


intro: |
  Experienced Product Manager with 15 years in technology and business. <br/><br/> Built products and end-customer solutions that are currently LIVE at Apple, IBM and NVIDIA. <br/><br/> Currently a Lead Product Manager in NVIDIA's Enterprise Product Group. Expertise in delivering technology-backed products with a focus on good engineering principles and clean code. <br/><br/> Successful in large-scale enterprise roles across India and the USA, adept at navigating diverse go-to-market motions.


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>NVIDIA</strong>: <br/>
                            • DGX Cloud MVP business model for Top-20 customers/Hyperscalar-level pre-training. <br/>
                            • Day 2 playbook for data manageibility and partnerships with CSP on ingress/egress and staging. <br/>
                            • 1000+ fine-tuning jobs on fine-tuning with DGX Cloud via Hugging Face front-end with pay-as-you-go B2B2B business model. <br/>
                            • Successful internal alignment on standardized API spec for GPU consumption in managed service mode via partners. <br/>
                            • 10+ model and data partners onboarded for NVIDIA Inference microservices (NIM) adoption.  <br/><br/>
   <strong>Apple</strong>:  <br/>
                            • Responsible for applying 2D Deep Learning models in Apple factories for Capex savings and yield improvements of Iphone Line of Business. <br/>
                            • Responsible for data movement to centralized data management and real time processing of model inference.  <br/>
                            • Managed global teams for building and deploying Infra for always-ON inference platform using on-prem and CSP utilities. <br/>
                            • Responsible for building data and model drift observability platform and flows.  <br/>
                            • Responsible for scaling the product from single Apple Line of Business to across all Apple products, resulting in $50M+ savings for Apple manufacturing.<br/><br/>
   <strong>IBM</strong>:    <br/>
                            • Responsible for setting up distributed data processing pipeline using Apache Spark on Hadoop Data lake. <br/>
                            • Responsible for working with Major CSPs to show value of IBM solution for fastest shuffle + sorting performance. <br/>
                            • Led team to put a streaming and batch processing pipeline for enterprise use-case with Apache Spark. <br/>
                            • Worked with research to optimize IBM compute architecture for contemporary workloads like Spark in-memory processing and Deep learning workloads. <br/>
                            • Awarded patents in the process of working with research around distributed processing and helping take IBM's effort to US National Laboratories. <br/>
                            • Got eligibility for Einstein Visa and got Green Card in Einstein visa category due to work done with IBM engineering and research teams and results delivered to enhance US technology.<br/><br/>
   
